version: 1
default_environment: dev
send_anonymous_usage_stats: false
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
  loaders:
  - name: target-sqlite
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-sqlite.git
  mappers:
  - name: my-own
    namespace: meltano_map_trafonsform
    pip_url: /map_trafo
    executable: meltano-map-transform
    mappings:
    - name: hash_email
      config:
        stream_maps:
          customers:
            id: id
            email:      # drop the PII field from RECORD and SCHEMA messages
            email_domain: email.split('@')[-1]
            email_hash: md5(config['hash_seed'] + email)
            non_beer: email
            __else__: null
        stream_map_config:
          hash_seed: 01AWZh7A6DzGm6iJZZ2
          __foobar__: ["email_hash","email_domain"]
          __beer__: ["non_beer"]
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-csv
        config:
          files:
          - entity: customers
            path: fixtures/customers.csv
            keys: [id]
      loaders:
      - name: target-sqlite
        config:
          batch_size: 200
          database: output/$MELTANO_EXTRACTOR_NAMESPACE.db



project_id: c0543dd9-8bc9-48ad-8f28-bbf0899d62b8
